<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pe.edu.pucp</groupId>
        <artifactId>sigmeta</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>sigmeta-ejecucion</artifactId>
    <packaging>jar</packaging>

    <name>SIGMETA Ejecucion</name>
    <description>Modulo de ejecucion. Clase main y pruebas de la capa de dominio.</description>

    <dependencies>
        <dependency>
            <groupId>pe.edu.pucp</groupId>
            <artifactId>sigmeta-dominio</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
